#!/usr/bin/env python

import sys

def factorize(n):
	factors = []
	for i in range(2, n // 2 + 1):
		if n % i == 0:
			factors.append((i, n // i))
	return (factors)
def main():
	if len(sys.argv) != 2:
		print("Usage: factors <file>")
		sys.exit(1)
	input_file = sys.argv[1]
	try:
		with open(input_file, 'r') as file:
			for line in file:
				n = int(line.strip())
				factorizations = factorize(n)
				for factorization in factorizations:
					print(f"{n}={factorization[0]}*
					{factorization[1]}")
	except FileNotFoundError:
		print(f"Error: File '{input_file}' not found.")
		sys.exit(1)
if __name__ == "__main__":
	main()
