#!/usr/bin/env python

def factors(filename):
    """
    Read a file containing natural numbers and print their factorizations.

    Args:
    - filename (str): The name of the file containing natural numbers, one per line.
    """
    with open(filename, 'r') as f:
        for line in f:
            n = int(line)
            factorizations = _factorize(n)
            for p, q in factorizations:
                print(f"{n}={p}*{q}")

def _factorize(n):
    """
    Factorize a number into a list of tuples representing pairs of factors (p, q).

    Args:
    - n (int): The number to be factorized.

    Returns:
    - list: List of tuples representing pairs of factors.
    """
    if n <= 1:
        return []
    factors = []
    i = 2
    while i * i <= n:
        if n % i == 0:
            n //= i
            factors.append((i, n))
            i = 2
        else:
            i += 1
            if n > 1:
                factors.append((n, 1))
                return factors
if __name__ == '__main__':
    import sys
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
        filename = sys.argv[1]
        factors(filename)
